# .github/workflows/main.yml

name: Python CI/CD with AWS CDK

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # =================================================================
  #  Continuous Integration (CI) Job
  #  This job runs on every push and pull request to main and develop.
  #  It installs dependencies, runs tests, and reports coverage.
  # =================================================================
  test:
    name: Run Unit Tests & Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13'] # Run tests on multiple Python versions

    steps:
      # 1. Checkout the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assuming you have a requirements.txt
          pip install pytest coverage # Install testing tools

      # 4. Run tests with coverage
      #    - Runs pytest on the 'tests/' directory.
      #    - Uses the coverage package to measure code coverage.
      #    - The `coverage report` command will display the results in the action's log.
      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest tests/
          coverage report

  # =================================================================
  #  Continuous Deployment (CD) Jobs
  #  These jobs deploy the AWS CDK stack to different environments.
  # =================================================================

  # --- Deployment to Playground Environment ---
  deploy-playground:
    name: Deploy to Playground
    needs: test # This job will only run if the 'test' job succeeds
    runs-on: ubuntu-latest
    # Condition: Only run on pushes to the 'develop' branch
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials for Playground
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PLAYGROUND_CICD_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.PLAYGROUND_CICD_AWS_SECRET }}
          aws-region: us-east-1 # <-- IMPORTANT: Change this to your desired AWS region

      - name: Install AWS CDK and Python dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: CDK Deploy to Playground
        run: |
          cdk deploy --context env=playground --require-approval never

  # --- Deployment to Preview Environment ---
  deploy-preview:
    name: Deploy to Preview
    needs: test
    runs-on: ubuntu-latest
    # This example uses a manual trigger for Preview.
    # You can change this to trigger on merges to a 'release' branch, for example.
    environment: preview # Defines a GitHub environment for protection rules
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Example: trigger on push to main

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials for Preview
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PREVIEW_CICD_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.PREVIEW_CICD_AWS_SECRET }}
          aws-region: us-east-1 # <-- IMPORTANT: Change this to your desired AWS region

      - name: Install AWS CDK and Python dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: CDK Deploy to Preview
        run: |
          cdk deploy --context env=preview --require-approval never

  # --- Deployment to Live Environment ---
  deploy-live:
    name: Deploy to Live
    needs: test
    runs-on: ubuntu-latest
    environment: live # Defines a GitHub environment for protection rules and manual approval
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials for Live
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.LIVE_CICD_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.LIVE_CICD_AWS_SECRET }}
          aws-region: us-east-1

      - name: Install AWS CDK and Python dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: CDK Deploy to Live
        run: |
          cdk deploy --context env=live --require-approval never
